apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-client
  namespace: consul-dc1
  labels:
    app: consul-client
spec:
  replicas: 5
  selector:
    matchLabels:
      app: consul-client
  template:
    metadata:
      labels:
        app: consul-client
    spec:
      containers:
      - name: consul
        image: hashicorp/consul-enterprise:1.20-ent
        command: ["consul", "agent", "-config-file=/consul/config/consul.hcl"]
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
          protocol: UDP
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8300
          name: server
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-logs
          mountPath: /var/log
        - name: consul-config
          mountPath: /consul/config
        env:
        - name: CONSUL_HTTP_TOKEN 
          valueFrom:
            secretKeyRef:
              name: consul-global-token-secret
              key: SecretID
        - name: CONSUL_LICENSE
          valueFrom:
            secretKeyRef:
              name: consul-licence
              key: consul.hclic
      - name: counting-service
        image: hashicorp/counting-service:0.0.2
        ports:
        - containerPort: 9001
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: promtail
        image: grafana/promtail
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
          - "-config.expand-env=true"
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail/
        - name: consul-logs
          mountPath: /var/log/
      volumes:
      - name: consul-data
        emptyDir: {}
      - name: consul-logs
        emptyDir: {}
      - name: consul-config
        configMap:
          name: consul-client1-config-dc1
      - name: promtail-config
        configMap:
          name: promtail-consul-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: counting-service
  namespace: consul-dc1
  labels:
    app: consul-client
spec:
  ports:
  - port: 9001
    name: http
  clusterIP: None
  selector:
    app: consul-client